### PR TITLE
Feature/procedural buttons

### PR DESCRIPTION
**Pull request by LeBogoo**
## Overview

This pull request introduces functionality for dynamic button generation and semi-dynamic confirmation modals. These enhancements are aimed at improving the flexibility and scalability of our UI components.

## Changes Included

1. **Dynamic Button Generation from JSON File:**
   - Implemented a feature that reads button configurations from a JSON file.
   - Buttons are generated dynamically based on the JSON data, allowing for easy updates and scalability.

2. **Semi-Dynamic Confirmation Modal:**
   - Adds a modal with customizable title, bits, and image.
   - Returns a promise that resolves to true or false based on user interaction with the "Yes" or "No" buttons.

### CODE REVIEW

**Comment by Alexejhero** [comment]
@Vedal987 Please review this at your earliest convenience, unfortunately my cat ate my github desktop so I can't checkout the PR to test

**Review by Alexejhero — APPROVED** [review]
LGTM!

**Comment by Alexejhero** [comment]
NVM

**Comment by Alexejhero** [comment]
I'm merging these changes in manually, you will be credited as a co-author in the next commit

**Comment by LeBogoo** [comment]
Sounds good!

**Pull request closed without merging**
